const express = require('express')
const cors = require('cors')
const {MongoClient} = require('mongodb')
const app=express()
app.use(cors())
app.use(express.json())
const client =new MongoClient('mongodb+srv://admin_2018:admin_2018@cluster0.dk0bqw7.mongodb.net/?retryWrites=true&w=majority')
client.connect()
const db = client.db('counselling1')
const col = db.collection('register')
//co1.insertOne({'student':"123"})
app.post('/register',(req, res)=>{
    col.insertOne(req.body)
    res.send('Inserted sucessfully')
})
app.get('/retrive', async (req,res)=>{
    const result = await col.find().toArray()
    console.log(result)
    res.send(result)
})
app.get('/',(req,res)=>{res.send('<h1>Hello</h1>')})
app.get('/about',(req,res)=>{res.send('<h1>About</h1>')})
app.listen('8000',()=>{console.log('Server is running')})